---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yin.
--- DateTime: 2025/10/18 16:40
---

-- 优惠券秒杀参与脚本
--keys[1]:coupon_seckill:stock:{activityId}
--keys[2]:coupon_seckill:participants:{activityId}
--argv[1]:userId
--argv[2]:quantity
--argv[3]:perUserLimit

--检查用户是否已经参与
local isParticipated = redis.call('sismember',KEYS[2],ARGV[1])
if isParticipated==1 then
    return {0,1} -- 1: 用户已经参与过
end

--检查库存是否充足
local stock = redis.call('get',KEYS[1])
if not stock then
    return {0,2} -- 2: 活动不存在
end

stock = tonumber(stock)
if not stock then
    return {0,2} -- 2: 活动不存在（库存数据无效）
end

local quantity = tonumber(ARGV[2])
local perUserLimit = tonumber(ARGV[3])

if stock < quantity then
    return {0,3} -- 3: 秒杀库存不足
end
if quantity > perUserLimit then
    return {0,4} -- 4: 超过限领数量
end

--扣减库存
local newStock = redis.call('decrby',KEYS[1],quantity)
if newStock <0 then
    --回滚库存
    redis.call('incrby',KEYS[1],quantity)
    return {0,3} -- 3: 秒杀库存不足
end

--记录用户参与
redis.call('sadd',KEYS[2],ARGV[1])
--设置过期时间（活动结束后清理）
redis.call('expire',KEYS[2],24*60*60)
return {1,0,newStock} -- 0: 成功