server:
  port: 8089

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    druid:
      driver-class-name: ${coffee.datasource.driver-class-name}
      url: jdbc:mysql://${coffee.datasource.host}:${coffee.datasource.port}/${coffee.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${coffee.datasource.username}
      password: ${coffee.datasource.password}
  redis:
    host: ${coffee.redis.host}
    port: ${coffee.redis.port}
    database: ${coffee.redis.database}
    password: ${coffee.redis.password}
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10分钟，单位毫秒
      cache-null-values: false
      key-prefix: "cache:"
      use-key-prefix: true

  # RabbitMQ配置
  rabbitmq:
    host: ${coffee.rabbitmq.host:localhost}
    port: ${coffee.rabbitmq.port:5672}
    username: ${coffee.rabbitmq.username:guest}
    password: ${coffee.rabbitmq.password:guest}
    virtual-host: ${coffee.rabbitmq.virtual-host:/}
    connection-timeout: 15000
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2

# 添加在这里 - 与 spring 同级
springfox:
  documentation:
    auto-startup: false

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coffee.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      coffee:
        mapper: debug
        service: info
        controller: info
    org.springframework.amqp: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){faint} %clr(%-5level) %clr(%logger{36}){cyan} %clr(-){faint} %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/coffee-server.log
    max-size: 100MB
    max-history: 30

coffee:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization
    # 设置用户令牌名称
    user-token-name: Authorization
    # 设置用户令牌加密时使用的秘钥
    user-secret-key: itcast
    # 设置用户令牌过期时间
    user-ttl: 7200000
  shop:
    address: 燕山大学
  baidu:
    ak: ${BAIDU_API_KEY:your-baidu-api-key}
  alioss:
    endpoint: ${coffee.alioss.endpoint}
    access-key-id: ${coffee.alioss.access-key-id}
    access-key-secret: ${coffee.alioss.access-key-secret}
    bucket-name: ${coffee.alioss.bucket-name}
  wechat:
    appid: ${coffee.wechat.appid}
    secret: ${coffee.wechat.secret}
    notify-url: ${coffee.wechat.notify-url}
    refund-notify-url: ${coffee.wechat.refund-notify-url}
  redis:
    seckill:
      prefix: "seckill:"
